name: app_pemrograman_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.3
  equatable: ^2.0.5
  firebase_auth: ^4.15.1
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  get: ^4.6.6
  http: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo-SB/Icon-SB.png"

flutter:
  assets:
  - assets/Carousel_Banner/
  - assets/Catalog_Short/
  - assets/Category/Bag/
  - assets/Category/Cap/
  - assets/Category/Fitness/
  - assets/Category/Misc/
  - assets/Category/Pants/
  - assets/Category/Shoe/
  - assets/Category/T-Shirt/
  - assets/Iconly/Setting.png
  - assets/Logo-SB/
  - assets/Misc/Refresh.png
  
  fonts:
  - family: Lato
    fonts:
      - asset: assets/Font/Lato/Lato-Regular.ttf
        weight: 400
      - asset: assets/Font/Lato/Lato-Italic.ttf
        weight: 400
      - asset: assets/Font/Lato/Lato-Bold.ttf
        weight: 700
      - asset: assets/Font/Lato/Lato-BoldItalic.ttf
        weight: 700

  - family: Oswald
    fonts:
      - asset: assets/Font/Oswald/static/Oswald-Regular.ttf
        weight: 400
      - asset: assets/Font/Oswald/static/Oswald-Bold.ttf
        weight: 700
  
  uses-material-design: true
